server:
  port: 9010
spring:
  application:
    name: backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.17.128:3306/z-link?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  data:
    redis:
      host: 192.168.17.128
      port: 6379
      timeout: 3000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表
  basic:
    enable: false

zlink:
  domain:
    default: zlink.ink:${server.port}
  bloom:
    exepctedInsertions: 10000000 # 预期1000万短链
    falseProbability: 0.01 # 1%误判率
    filterName: zlink_bloom_filter
    batchSize: 1000 # 每次处理数量
    loadTimeout: 300 # 加载超时时间（秒）
    asyncLoad: true # 是否异步加载
    memoryThreshold: 0.8 # 内存使用阈值
    executor:
      corePoolSize: 4
      maxPoolSize: 8
      queueCapacity: 1000
      keepAliveSeconds: 60
      awaitTerminationSeconds: 30
      threadNamePrefix: zlink-bloom-filter-executor
